// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _8Mission.Models;

namespace _8Mission.Migrations
{
    [DbContext(typeof(TaskContext))]
    [Migration("20230222203328_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("_8Mission.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category_Name")
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryID");

                    b.ToTable("categories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            Category_Name = "Home"
                        },
                        new
                        {
                            CategoryID = 2,
                            Category_Name = "School"
                        },
                        new
                        {
                            CategoryID = 3,
                            Category_Name = "Work"
                        },
                        new
                        {
                            CategoryID = 4,
                            Category_Name = "Church"
                        });
                });

            modelBuilder.Entity("_8Mission.Models.Tasks", b =>
                {
                    b.Property<int>("TaskID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryID")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Completed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Due_Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quadrant")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Task_Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TaskID");

                    b.HasIndex("CategoryID");

                    b.ToTable("tasks");

                    b.HasData(
                        new
                        {
                            TaskID = 1,
                            CategoryID = 1,
                            Completed = false,
                            Due_Date = "2005-12-01",
                            Quadrant = 1,
                            Task_Name = "Crises"
                        },
                        new
                        {
                            TaskID = 2,
                            CategoryID = 1,
                            Completed = false,
                            Due_Date = "2005-12-01",
                            Quadrant = 2,
                            Task_Name = "Relationship Building"
                        },
                        new
                        {
                            TaskID = 3,
                            CategoryID = 1,
                            Completed = false,
                            Due_Date = "2005-12-01",
                            Quadrant = 3,
                            Task_Name = "Interruptions"
                        },
                        new
                        {
                            TaskID = 4,
                            CategoryID = 1,
                            Completed = false,
                            Due_Date = "2005-12-01",
                            Quadrant = 4,
                            Task_Name = "Busy Work"
                        });
                });

            modelBuilder.Entity("_8Mission.Models.Tasks", b =>
                {
                    b.HasOne("_8Mission.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
